version: "2"
checks:
  argument_count:
    enabled: true
  file_lines:
    enabled: true
  method_count:
    enabled: true
  return_count:
    enabled: true

exclude_paths:
  - "node_modules/**"
  - "coverage/**"

engines:
  eslint:
    enabled: true
    config:
      extensions:
      - .js
      - .jsx

ratings:
  paths:
  - "**.js"
  - "**.jsx"

test_reporter:
  id: "cc-test-reporter"
  coverage_file:
    - "coverage/lcov.info"
