# Example .hound.yml for a Node.js, Express, Postgres, and React on our e-commerce project
eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore

jscs:
  enabled: true
  config_file: .jscsrc

npm:
  enabled: true

# React specific rules
react:
  enabled: true
  jsx_file_extensions:
    - ".jsx"
    - ".tsx"

# SQL linting
eslint_sql:
  enabled: true
  config_file: .eslintrc-sql.json
