version: 2.1

orbs:
  node: circleci/node@4.0.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:

    executor:
      name: node/default

      executor: node-executor
    environment:
      CC_TEST_REPORTER_ID: b996f145a438f80141cfcc86bb35a2c212a2a24c394abee18da6add05eaaee7e
    steps:
      - checkout
      # - node/install-packages
      - run: npm install
      - run:
          name: Initialize Code Climate test reporter
          command: cc-test-reporter before-build
      - run:
          name: Run Tests with Coverage
          command: npm run test:coverage
      - run:
          name: Format Coverage Report
          command: nyc report --reporter=text-lcov > coverage.lcov
      - run:
          name: Upload Coverage Report to Code Climate
          command: |
            cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage.lcov
            cc-test-reporter upload-coverage
      - run:
          name: Initialize Code Climate test reporter
          command: cc-test-reporter before-build
      - run:
          name: Run Tests with Coverage
          command: npm run test:coverage
      - run:
          name: Format Coverage Report
          command: nyc report --reporter=text-lcov > coverage.lcov
      - run:
          name: Upload Coverage Report to Code Climate
          command: |
            cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage.lcov
            cc-test-reporter upload-coverage

  deploy:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Build Project
          command: tsc

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

