version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm test
workflows:
  version: 2
  build-deploy:
    jobs:
      - build