version: 2.1

orbs:
  node: circleci/node@4.0.0
  coveralls: coveralls/coveralls@2.1.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Tests
          command: npm test

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run:
          name: Install TypeScript
          command: npm install -g typescript
      - run:
          name: Build Project
          command: tsc

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
