version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Build Project
          command: npm run build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
