version: 2.1


orbs:
  node: circleci/node@4.0.0


jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      # - node/install-packages
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and generate coverage report
          command: npm test 
      - run:
          name: Install CodeClimate Test Reporter
          command: npm install -g codeclimate-test-reporter
      - run:
          name: Upload coverage to CodeClimate
          command: |
            codeclimate-test-reporter < coverage/lcov.info
          environment:
            CODECLIMATE_REPO_TOKEN: $CODECLIMATE_REPO_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
